### ISSUE TITLE
Problem in Catkin build 

### ISSUE THREAD

**Issue by Gireeshsuresh** [BCLab-UNM/SwarmBaseCode-ROS#129]
Hello Guys,
I am participating in the Virtual challenge ( First time). After installing ROS and following the steps given in https://github.com/BCLab-UNM/SwarmBaseCode-ROS , I cloned the git repository . While I tried to catkin build , I am getting some error. Kindly help. 

The error I am getting is as shown below. Please let m know if I am missing something or doing something wrong. Thanks in Advance.

=================================================================================

 
dexter@Gireesh-XPS: ~/SwarmBaseCode-ROS$ catkin build
-------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/kinetic
Workspace:                   /home/dexter/SwarmBaseCode-ROS
-------------------------------------------------------------------
Source Space:       [exists] /home/dexter/SwarmBaseCode-ROS/src
Log Space:          [exists] /home/dexter/SwarmBaseCode-ROS/logs
Build Space:        [exists] /home/dexter/SwarmBaseCode-ROS/build
Devel Space:        [exists] /home/dexter/SwarmBaseCode-ROS/devel
Install Space:      [unused] /home/dexter/SwarmBaseCode-ROS/install
DESTDIR:            [unused] None
-------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------
[build] Found '14' packages in 0.0 seconds.                                                                                                                   
[build] Package table is up to date.                                                                                                                          
Starting  >>> abridge                                                                                                                                         
Starting  >>> apriltags                                                                                                                                       
Starting  >>> diagnostics                                                                                                                                     
Starting  >>> gazebo_plugins                                                                                                                                  
Starting  >>> sbridge                                                                                                                                         
Starting  >>> swarmie_msgs                                                                                                                                    
Starting  >>> ublox_serialization                                                                                                                             
Starting  >>> usb_cam                                                                                                                                         
Finished  <<< ublox_serialization                [ 0.1 seconds ]                                                                                              
Starting  >>> ublox_msgs                                                                                                                                      
Finished  <<< abridge                            [ 0.2 seconds ]                                                                                              
Finished  <<< usb_cam                            [ 0.2 seconds ]                                                                                              
Finished  <<< apriltags                          [ 0.2 seconds ]                                                                                              
Starting  >>> apriltags_ros                                                                                                                                   
Finished  <<< gazebo_plugins                     [ 0.3 seconds ]                                                                                              
Finished  <<< sbridge                            [ 0.3 seconds ]                                                                                              
Finished  <<< diagnostics                        [ 0.7 seconds ]                                                                                              
______________________________________________________________________________________________________________________________________________________________
Errors     << swarmie_msgs:make /home/dexter/SwarmBaseCode-ROS/logs/swarmie_msgs/build.make.008.log                                                           
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/swarmie_msgs/include/swarmie_msgs/Waypoint.h] Error 1
make[1]: *** [CMakeFiles/swarmie_msgs_generate_messages_cpp.dir/all] Error 2
make: *** [all] Error 2
cd /home/dexter/SwarmBaseCode-ROS/build/swarmie_msgs; catkin build --get-env swarmie_msgs | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..............................................................................................................................................................
Failed     << swarmie_msgs:make                  [ Exited with code 2 ]                                                                                       
Failed    <<< swarmie_msgs                       [ 0.4 seconds ]                                                                                              
Abandoned <<< behaviours                         [ Unrelated job failed ]                                                                                     
Abandoned <<< rqt_rover_gui                      [ Unrelated job failed ]                                                                                     
Abandoned <<< ublox_gps                          [ Unrelated job failed ]                                                                                     
______________________________________________________________________________________________________________________________________________________________
Errors     << apriltags_ros:make /home/dexter/SwarmBaseCode-ROS/logs/apriltags_ros/build.make.005.log                                                         
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/apriltags_ros/include/apriltags_ros/AprilTagDetection.h] Error 1
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/apriltags_ros/include/apriltags_ros/AprilTagDetectionArray.h] Error 1
make[1]: *** [CMakeFiles/apriltags_ros_generate_messages_cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/dexter/SwarmBaseCode-ROS/build/apriltags_ros; catkin build --get-env apriltags_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..............................................................................................................................................................
Failed     << apriltags_ros:make                 [ Exited with code 2 ]                                                                                       
Failed    <<< apriltags_ros                      [ 0.8 seconds ]                                                                                              
______________________________________________________________________________________________________________________________________________________________
Errors     << ublox_msgs:make /home/dexter/SwarmBaseCode-ROS/logs/ublox_msgs/build.make.007.log                                                               
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/AidALM.h] Error 1
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/AidHUI.h] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/AidEPH.h] Error 1
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/CfgANT.h] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
    import em
ModuleNotFoundError: No module named 'em'
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/CfgCFG.h] Error 1
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/CfgGNSS.h] Error 1
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/CfgMSG.h] Error 1
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 41, in <module>
    import genmsg.template_tools
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 39, in <module>
    import em
ModuleNotFoundError: No module named 'em'
make[2]: *** [/home/dexter/SwarmBaseCode-ROS/devel/.private/ublox_msgs/include/ublox_msgs/CfgNAV5.h] Error 1
make[1]: *** [CMakeFiles/ublox_msgs_generate_messages_cpp.dir/all] Error 2
make: *** [all] Error 2
cd /home/dexter/SwarmBaseCode-ROS/build/ublox_msgs; catkin build --get-env ublox_msgs | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..............................................................................................................................................................
Failed     << ublox_msgs:make                    [ Exited with code 2 ]                                                                                       
Failed    <<< ublox_msgs                         [ 1.2 seconds ]                                                                                              
[build] Summary: 7 of 13 packages succeeded.                                                                                                                  
[build]   Ignored:   1 packages were skipped or are blacklisted.                                                                                              
[build]   Warnings:  None.                                                                                                                                    
[build]   Abandoned: 3 packages were abandoned.                                                                                                               
[build]   Failed:    3 packages failed.                                                                                                                       
[build] Runtime: 2.3 seconds total.                                                                                                                           
dexter@Gireesh-XPS:~/SwarmBaseCode-ROS$

**Comment by Gireeshsuresh** [comment]
Solved the issue.
" pip install empy "

**Comment by Gireeshsuresh** [comment]
Solved the issue using " pip install empy "
